import test from 'node:test';
import assert from 'node:assert/strict';
const engine = await import('../public/shared/engine.js').catch(() => ({}));
const config = await import('../public/shared/config.js').catch(() => ({}));
const maps = await import('../public/shared/maps.js').catch(() => ({}));
const roster = () => ['knight','ogre','warlock','jester','bull','prince'].map((hero,i)=>({id:`p${i}`,name:hero,hero,team:i<3?0:1,bot:false}));
function game(mode='deathmatch') { assert.equal(typeof engine.createGame,'function'); const g=engine.createGame({players:roster(),mode});g.map.obstacles=[];g.map.bushes=[];g.players.forEach((p,i)=>{p.x=2+i*4;p.y=3;p.shield=0;p.hp=p.maxHp=[15,25,15,12,23,17][i];});return g; }
function advance(g, seconds, inputs={}) { for(let i=0;i<Math.round(seconds*30);i++) engine.stepGame(g,1/30,inputs); }
function duel(g,a=0,b=3) { g.players.forEach((p,i)=>{p.x=2+i*4;p.y=16;});const x=g.players[a],y=g.players[b];x.x=10;x.y=9;y.x=11;y.y=9;return [x,y]; }
test('exact hero values and three original mirrored maps',()=>{assert.ok(config.HEROES);assert.deepEqual(Object.values(config.HEROES).map(h=>h.hp),[40,65,38,32,60,42]);assert.deepEqual(Object.values(config.HEROES).map(h=>h.charge),[14,24,22,18,26,24]);for(const id of ['meadow','graveyard','beach']){const m=maps.createMap(id);assert.equal(m.width,28);assert.equal(m.height,18);assert.ok(m.obstacles.length>4);for(const o of m.obstacles){assert.ok(m.obstacles.some(b=>b.x===28-o.x&&b.y===o.y));assert.equal(o.hp,o.permanent?null:6);}}});
test('normal effective enemy hero damage charges, friendly attacks do not',()=>{const g=game();const [a,b]=duel(g);engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.equal(b.hp,9);assert.equal(a.charge,3);assert.equal(g.scores[0],0);a.cooldown=0;b.team=0;engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.equal(b.hp,9);assert.equal(a.charge,3);});
test('death preserves charge, scores killer, respawns after 5 seconds with shield',()=>{const g=game();const [a,b]=duel(g);b.hp=2;b.charge=5;engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.equal(a.charge,2);assert.equal(b.hp,0);assert.equal(b.charge,5);assert.equal(g.scores[0],1);advance(g,4.9);assert.equal(b.hp,0);advance(g,.2);assert.equal(b.hp,b.maxHp);assert.ok(b.shield>1.8);});
test('knight ultimate hits enemy once, breaks cover, gives no charge',()=>{const g=game();const [a,b]=duel(g);a.charge=config.HEROES[a.hero].charge;g.map.obstacles=[{id:'cover',x:10.6,y:9,w:.3,h:1,hp:6,maxHp:6,permanent:false}];engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,1);assert.equal(b.hp,5);assert.equal(a.charge,0);assert.equal(g.map.obstacles.length,0);});
test('ogre ultimate gives exactly five 2-damage pulses',()=>{const g=game();const [a,b]=duel(g,1,4);b.x=15;a.charge=config.HEROES[a.hero].charge;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,5.2);assert.equal(b.hp,13);assert.equal(a.charge,0);assert.equal(g.zones.length,0);});
test('warlock ultimate heals actual damage capped at max hp',()=>{const g=game();const [a,b]=duel(g,2,3);a.hp=14;a.charge=config.HEROES[a.hero].charge;b.hp=3;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,.3);assert.equal(a.hp,15);assert.equal(a.charge,0);assert.equal(b.hp,0);});
test('prince explosion never doubles its direct impact',()=>{const g=game();const [a,b]=duel(g,5,1);b.x=12;a.team=1;b.team=0;a.charge=config.HEROES[a.hero].charge;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,.5);assert.ok(b.hp>=0);const hits=g.events.filter(e=>e.type==='damage'&&e.target===b.id);assert.ok(hits.length<=5);assert.ok(hits.every(e=>e.value<=7));assert.equal(a.charge,0);});
test('concealment hides only distant enemies and snapshot is detached',()=>{const g=game();const b=g.players[3];g.map.bushes=[{x:b.x,y:b.y,w:2,h:2}];assert.ok(!engine.visiblePlayers(g,0).some(p=>p.id===b.id));b.revealedUntil=2;assert.ok(engine.visiblePlayers(g,0).some(p=>p.id===b.id));const s=engine.snapshotFor(g,0);s.players[0].hp=1;assert.notEqual(g.players[0].hp,1);});
test('malicious inputs and large dt cannot create nonfinite state',()=>{const g=game();engine.stepGame(g,NaN,{p0:{mx:Infinity,my:NaN,angle:Infinity,attack:true,ult:true}});advance(g,1,{p0:{mx:Infinity,my:NaN,angle:Infinity,attack:true}});for(const p of g.players)for(const k of ['x','y','hp','angle'])assert.ok(Number.isFinite(p[k]));});
test('flags collect, deliver, drop and reset without kill victory points',()=>{const g=game('flags');const p=g.players[0];p.x=g.flags[0].x;p.y=g.flags[0].y;engine.stepGame(g,1/30);assert.ok(p.carrying);p.x=g.map.portals[0].x;p.y=g.map.portals[0].y;engine.stepGame(g,1/30);assert.equal(g.scores[0],1);assert.equal(p.carrying,null);});
test('ties overtime, first deathmatch kill wins and scoreless overtime draws',()=>{const g=game();g.remaining=.01;engine.stepGame(g,1/30);assert.equal(g.overtime,true);assert.equal(g.phase,'playing');const [a,b]=duel(g);b.hp=1;engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.equal(g.winner,0);assert.equal(g.phase,'finished');const h=game('flags');h.remaining=.01;engine.stepGame(h,1/30);h.remaining=.01;engine.stepGame(h,1/30);assert.equal(h.phase,'finished');assert.equal(h.winner,null);});
test('simultaneous orb destruction draws and ordinary orb damage never charges',()=>{const g=game('orb');g.orbs.forEach(o=>o.hp=0);engine.stepGame(g,1/30);assert.equal(g.phase,'finished');assert.equal(g.winner,null);const h=game('orb');const p=h.players[0],o=h.orbs[1];p.x=o.x-1;p.y=o.y;engine.stepGame(h,1/30,{[p.id]:{angle:0,attack:true}});assert.equal(o.hp,117);assert.equal(p.charge,0);});
test('seeded objective-aware bots finish every mode with finite state',()=>{for(const mode of ['deathmatch','flags','orb']){const players=roster().map(p=>({...p,bot:true}));const g=engine.createGame({players,mode,seed:17});advance(g,271);assert.equal(g.phase,'finished',mode);assert.ok(g.players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));assert.ok(g.events.length<=100);}});
test('jester normal shoots three successive projectiles and box waits 0.8 seconds',()=>{const g=game();const [a,b]=duel(g,3,1);engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});advance(g,.1);assert.equal(b.hp,23);advance(g,.3);assert.equal(b.hp,19);a.charge=config.HEROES[a.hero].charge;b.x=13;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,.7);assert.equal(b.hp,19);advance(g,.1);assert.equal(b.hp,9);});
test('bull dash hits once, breaks cover, pushes safely and stops at permanent walls',()=>{const g=game();const [a,b]=duel(g,4,1);b.x=11.5;g.map.obstacles=[{id:'break',x:10.8,y:9,w:.2,h:1,hp:6,permanent:false},{id:'stop',x:12.8,y:9,w:.4,h:3,hp:null,permanent:true}];a.charge=config.HEROES[a.hero].charge;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,.5);assert.equal(b.hp,12);assert.equal(g.map.obstacles.length,1);assert.ok(a.x<12.3);assert.ok(b.x<12.3);assert.equal(a.charge,0);});
test('permanent cover stops wave and moving players',()=>{const g=game();const [a,b]=duel(g);g.map.obstacles=[{id:'solid',x:10.5,y:9,w:.2,h:4,hp:null,permanent:true}];a.charge=config.HEROES[a.hero].charge;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});advance(g,1,{[a.id]:{mx:1}});assert.equal(b.hp,12);assert.ok(a.x<10.2);assert.equal(g.map.obstacles[0].hp,null);});
test('carried flags drop on death and ground flags reset after fifteen seconds',()=>{const g=game('flags');const [a,b]=duel(g);const f=g.flags[0];b.carrying=f.id;f.carrier=b.id;b.hp=1;engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.equal(b.carrying,null);assert.equal(g.scores[0],0);a.x=2;a.y=2;advance(g,15.1);assert.equal(f.carrier,null);assert.equal(f.x,f.homeX);assert.equal(f.y,f.homeY);assert.ok(g.flags.filter(f=>!f.carrier).length<=3);});
test('orb expiration compares own health and overtime expires as draw',()=>{const g=game('orb');g.orbs[1].hp=100;g.remaining=.001;engine.stepGame(g,1/30);assert.equal(g.winner,0);const h=game('orb');h.remaining=.001;engine.stepGame(h,1/30);assert.ok(h.overtime);h.remaining=.001;engine.stepGame(h,1/30);assert.equal(h.phase,'finished');assert.equal(h.winner,null);});
test('protected spawn blocks intrusion and invulnerability cancels on attack',()=>{const g=game();const p=g.players[0],enemy=g.players[3];p.x=23;p.y=9;enemy.x=26;enemy.y=9;enemy.shield=2;advance(g,1,{[p.id]:{mx:1,my:0,angle:0,attack:true}});assert.ok(p.x<=24);assert.equal(enemy.hp,12);engine.stepGame(g,1/30,{[enemy.id]:{angle:Math.PI,attack:true}});assert.equal(enemy.shield,0);});
test('null and primitive player inputs are safely ignored',()=>{const g=game();assert.doesNotThrow(()=>engine.stepGame(g,1/30,{p0:null,p1:42,p2:'invalid'}));assert.ok(g.players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.angle)));});
test('one royal arrow applies exactly one explosion hit to its direct target',()=>{const g=game();const [a,b]=duel(g,5,1);b.x=12;a.charge=config.HEROES[a.hero].charge;engine.stepGame(g,1/30,{[a.id]:{angle:0,ult:true}});assert.equal(g.projectiles.length,5);g.projectiles=g.projectiles.filter(s=>Math.abs(s.vy)<.01);advance(g,.25);assert.equal(b.hp,18);assert.equal(g.events.filter(e=>e.type==='damage'&&e.target===b.id).length,1);});
test('ordinary melee and every ordinary projectile leave destructible cover intact',()=>{for(const index of [0,1,2,3,4,5]){const g=game();const p=g.players[index];p.x=10;p.y=9;g.map.obstacles=[{id:'cover',x:10.7,y:9,w:.3,h:2,hp:6,maxHp:6,permanent:false}];engine.stepGame(g,1/30,{[p.id]:{angle:0,attack:true}});advance(g,.5);assert.equal(g.map.obstacles[0]?.hp,6,p.hero);}});
test('snapshot conceals carried flags and pickup events with their hidden carrier',()=>{const g=game('flags'),p=g.players[3],f=g.flags[0];p.x=f.x;p.y=f.y;g.map.bushes=[{x:p.x,y:p.y,w:3,h:3}];engine.stepGame(g,1/30);assert.equal(p.carrying,f.id);const s=engine.snapshotFor(g,0);assert.ok(!s.players.some(x=>x.id===p.id));assert.ok(!s.flags.some(x=>x.id===f.id));assert.ok(!s.events.some(e=>e.type==='pickup'&&e.team===1));const ally=engine.snapshotFor(g,1);assert.ok(ally.flags.some(x=>x.id===f.id));assert.ok(ally.events.some(e=>e.type==='pickup'));});
test('first overtime flag delivery wins even when team one delivers before team zero',()=>{const g=game('flags');g.remaining=.001;engine.stepGame(g,1/30);for(const [i,pi] of [[0,3],[1,0]]){const p=g.players[pi],f=g.flags[i];p.x=g.map.portals[p.team].x;p.y=9;p.carrying=f.id;f.carrier=p.id;}engine.stepGame(g,1/30);assert.deepEqual(g.events.filter(e=>e.type==='objective').map(e=>e.team),[1,0]);assert.equal(g.winner,1);});
test('first overtime melee kill beats a later opposing projectile kill',()=>{const g=game();g.remaining=.001;engine.stepGame(g,1/30);g.players.forEach((p,i)=>{p.x=2+i*4;p.y=16;});const a=g.players[4],v=g.players[0],archer=g.players[2],other=g.players[3];a.x=10;a.y=9;v.x=11;v.y=9;v.hp=1;other.x=20;other.y=9;other.hp=1;g.projectiles.push({id:'preexisting',x:19.8,y:9,vx:14,vy:0,team:0,owner:archer.id,kind:'magic',damage:4,ultimate:false,remaining:2,hit:[],r:.12});engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.deepEqual(g.events.filter(e=>e.type==='death').map(e=>e.team),[0,1]);assert.equal(g.winner,1);});
test('prototype names normalize to valid mode map and hero defaults',()=>{for(const key of ['toString','constructor','__proto__']){const g=engine.createGame({mode:key,mapId:key,players:roster().map(p=>({...p,hero:key,bot:true}))});assert.equal(g.mode,'deathmatch');assert.equal(g.map.id,'meadow');assert.ok(g.players.every(p=>p.hero==='knight'&&p.hp===40));advance(g,2);assert.ok(g.players.every(p=>Number.isFinite(p.hp)&&Number.isFinite(p.x)));}});
test('melee deaths start at exactly five seconds regardless of victim loop position',()=>{for(const [ai,bi] of [[0,3],[4,1]]){const g=game(),[a,b]=duel(g,ai,bi);b.hp=1;engine.stepGame(g,1/30,{[a.id]:{angle:0,attack:true}});assert.equal(b.respawn,5);advance(g,149/30);assert.equal(b.hp,0);engine.stepGame(g,1/30);assert.equal(b.hp,b.maxHp);assert.equal(b.shield,2);}});
test('finished snapshots include all six results while live snapshots conceal enemies',()=>{const g=game(),p=g.players[3];g.map.bushes=[{x:p.x,y:p.y,w:2,h:2}];p.stats.kills=7;p.stats.damage=41;assert.ok(!engine.snapshotFor(g,0).players.some(x=>x.id===p.id));g.phase='finished';g.winner=1;const s=engine.snapshotFor(g,0);assert.equal(s.players.length,6);assert.deepEqual(s.players.find(x=>x.id===p.id).stats,p.stats);});
test('seeded flag placement varies reproducibly and avoids occupied neutral points',()=>{const layouts=new Set();for(let seed=1;seed<=12;seed++){const make=()=>engine.createGame({mode:'flags',players:roster(),seed});const g=make();assert.deepEqual(g.flags,make().flags);assert.notDeepEqual({x:g.flags[0].x,y:g.flags[0].y},{x:g.flags[1].x,y:g.flags[1].y});layouts.add(g.flags.map(f=>f.y).join(','));g.players.forEach(p=>{p.x=2;p.y=2;});advance(g,15.1);assert.equal(new Set(g.flags.map(f=>`${f.x},${f.y}`)).size,3);assert.ok(g.flags.every(f=>g.map.flagPoints.some(q=>q.x===f.x&&q.y===f.y)));}assert.ok(layouts.size>1);});
